# Remap prefix from `Ctrl+B` to `Ctrl+A`
unbind C-b
set-option -g prefix C-a
bind C-a send-prefix

# Split panes easily using intuitive visual shortcuts
# Ctrl+A followed by | splits vertically. Ctrl+A followed by - splits horizontally.
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Enable mouse mode for quick scroll
set -g mouse on

# Stop window auto-renaming so your names stick
set-option -g allow-rename off

# Ensure 256-color support inside terminal sessions
set -g default-terminal "screen-256color"

# Bind Ctrl+A followed by Ctrl+F to open a floating file finder
bind-key C-f run-shell "tmux popup -E -w 80% -h 80% 'fzf'"
